---
title: "**Chapter 4. Clustering and classification**"
author: "Anastasija Dmitrijeva"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
---

# **Chapter 4. Clustering and classification**

```{r}

library(dplyr)
library(ggplot2)
library("MASS")

data("Boston")
str(Boston)
dim(Boston)

# I've load the Boston data from the MASS package. This data set has 506 rows and 14 columns. It represents housing Values in suburbs of Boston.


summary(Boston)
pairs(Boston)

# A graphical overview of the data and summaries of the variables in the data can be seen. They are distributed normally.

boston_scaled <- scale(Boston)

summary(boston_scaled)

# Dataset standardization and summaries of the scaled data

boston_scaled <- as.data.frame(boston_scaled)

summary(boston_scaled["crim"])

b <- boston_scaled["crim"]

bins <- quantile(b)

crime <- cut(boston_scaled$crim, breaks = bins, include.lowest = TRUE, labels = c("low", "med_low", "med_high", "high"))

boston_scaled <- dplyr::select(boston_scaled, -crim)

n <- nrow(boston_scaled)

ind <- sample(n,  size = n * 0.8)

train <- boston_scaled[ind,]

test <- boston_scaled[-ind,]

# Creattion of a categorical variable of the crime rate in the Boston dataset (from the scaled crime rate). Quantiles are used as the break points in the categorical variable. Old crime rate variable is dropped from the dataset. Dataset is divided to train and test sets, so that 80% of the data belongs to the train set. 

lda.fit <- lda(crime ~ ., data = train)

plot(lda.fit)

# LDA (bi)plot.



