---
title: "**Chapter 5. Dimensionality reduction techniques**"
author: "Anastasija Dmitrijeva"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4

---

# **Chapter 5. Dimensionality reduction techniques**

```{r}

human <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/human2.txt", sep = ",", header = TRUE)

# Even though I have made a data wrangling part and my dataset has 155 observations and 8 variables, I will use dataset provided by link to avoid mistakes. For some reasons, my dataset does not work in this script. Below you can see a graphical overview of the data and summaries of the variables in the data.

plot(human)
summary(human)

# Principal component analysis (PCA) performed on the not standardized human data and a biplot displaying the observations by the first two principal components (PC1 coordinate in x-axis, PC2 coordinate in y-axis), along with arrows representing the original variables.

pca_human <- prcomp(human)

biplot(pca_human, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

# Standardization of the variables in the human data. It can be seen that the results of both analysis (with and without standardizing) are different. This is because PCA is sensitive to the scales of measures.

human_std <- scale(human)

pca_human_std <- prcomp(human_std)

summary(pca_human_std)

biplot(pca_human_std, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

# Based on the results it can be seen that there is low correlation between the ratio of labour force participation of females and males in each country and maternal mortality ratio, adolescent birth rate, expected years of schooling, life expectancy at birth, the ratio of Female and Male populations with secondary education in each country, Gross National Income GNI per Capita, and between percent representation in Parliament and maternal mortality ratio, adolescent birth rate, expected years of schooling, life expectancy at birth, the ratio of Female and Male populations with secondary education in each country, Gross National Income GNI per Capita. There is high correlation between percent representation in Parliament and the ratio of labour force participation of females and males in each country. Additionally, there is high correlation between maternal mortality ratio and adolescent birth rate, between expected years of schooling, life expectancy at birth, the ratio of Female and Male populations with secondary education in each country and Gross National Income GNI per Capita.

library(FactoMineR)
library(ggplot2)
library(dplyr)
library(tidyr)

data(tea)
str(tea)
dim(tea)

keep_columns <- c("Tea", "How", "how", "sugar", "where", "lunch")

tea_time <- dplyr::select(tea, one_of(keep_columns))

gather(tea_time) %>% ggplot(aes(value)) + facet_wrap("key", scales = "free") + geom_bar() + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))

mca <- MCA(tea_time, graph = FALSE)

summary(mca)

plot(mca, invisible=c("ind"), habillage = "quali")